### ISSUE TITLE
Error patching SHENZHEN I/O.

### ISSUE THREAD

**Issue by walkerKemp** [gtw123/ShenzhenMod#11]
Running `ShenzhenMod.exe` on Windows, clicking "Install" caused this error, this is the correct path. Shenzhen IO is up-to-date
![error](https://user-images.githubusercontent.com/36144194/107163589-52bc5b80-6978-11eb-80e2-109f15c3df10.png)
I asked about this in a discord server and somebody said something along the lines of "Recalculating hashes" but I don't exactly understand what that means.
Thanks

**Comment by JetBox** [comment]
Just came to say I tried modding the game tonight and ran into the same problem. I haven't tried this yet, but I'm thinking that it could be a version issue, not sure though.

**Comment by gtw123** [comment]
Yeah, it's just probably just that there's been an update to the game and so the hash has changed. It should just be a case of adding in the new hash, then checking the mod still installs and works correctly. I'll take a look later today.

**Comment by gtw123** [comment]
OK, it should be working now, at least with the latest Steam version. If anyone's having the same issue with the GOG version, send me the hash from the ShenzhenMod log file and I can add support for that too.

**Comment by the43rddev** [comment]
Same issue with GOG, here's the log from ShenzhenMod: https://pastebin.com/8zqjy1Ws
